[2025-09-27T06:26:13.962+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_optimization_suggestions.query_influx_data manual__2025-09-27T06:26:08.885187+00:00 [queued]>
[2025-09-27T06:26:13.971+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_optimization_suggestions.query_influx_data manual__2025-09-27T06:26:08.885187+00:00 [queued]>
[2025-09-27T06:26:13.973+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-09-27T06:26:13.996+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): query_influx_data> on 2025-09-27 06:26:08.885187+00:00
[2025-09-27T06:26:14.013+0000] {standard_task_runner.py:60} INFO - Started process 570 to run task
[2025-09-27T06:26:14.035+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'daily_optimization_suggestions', 'query_influx_data', 'manual__2025-09-27T06:26:08.885187+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/optimization_dag.py', '--cfg-path', '/tmp/tmp05y6rer_']
[2025-09-27T06:26:14.045+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask query_influx_data
[2025-09-27T06:26:14.326+0000] {task_command.py:423} INFO - Running <TaskInstance: daily_optimization_suggestions.query_influx_data manual__2025-09-27T06:26:08.885187+00:00 [running]> on host 6c490fe88578
[2025-09-27T06:26:14.447+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='daily_optimization_suggestions' AIRFLOW_CTX_TASK_ID='query_influx_data' AIRFLOW_CTX_EXECUTION_DATE='2025-09-27T06:26:08.885187+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-27T06:26:08.885187+00:00'
[2025-09-27T06:26:14.579+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/optimization_dag.py", line 26, in query_influx_data
    df = query_api.query_data_frame(query=query, org=INFLUX_ORG)
  File "/home/airflow/.local/lib/python3.8/site-packages/influxdb_client/client/query_api.py", line 259, in query_data_frame
    _generator = self.query_data_frame_stream(query, org=org, data_frame_index=data_frame_index, params=params,
  File "/home/airflow/.local/lib/python3.8/site-packages/influxdb_client/client/query_api.py", line 299, in query_data_frame_stream
    response = self._query_api.post_query(org=org, query=self._create_query(query, self.default_dialect, params,
  File "/home/airflow/.local/lib/python3.8/site-packages/influxdb_client/service/query_service.py", line 285, in post_query
    (data) = self.post_query_with_http_info(**kwargs)  # noqa: E501
  File "/home/airflow/.local/lib/python3.8/site-packages/influxdb_client/service/query_service.py", line 311, in post_query_with_http_info
    return self.api_client.call_api(
  File "/home/airflow/.local/lib/python3.8/site-packages/influxdb_client/_sync/api_client.py", line 343, in call_api
    return self.__call_api(resource_path, method,
  File "/home/airflow/.local/lib/python3.8/site-packages/influxdb_client/_sync/api_client.py", line 173, in __call_api
    response_data = self.request(
  File "/home/airflow/.local/lib/python3.8/site-packages/influxdb_client/_sync/api_client.py", line 388, in request
    return self.rest_client.POST(url,
  File "/home/airflow/.local/lib/python3.8/site-packages/influxdb_client/_sync/rest.py", line 311, in POST
    return self.request("POST", url,
  File "/home/airflow/.local/lib/python3.8/site-packages/influxdb_client/_sync/rest.py", line 261, in request
    raise ApiException(http_resp=r)
influxdb_client.rest.ApiException: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': 'v2.7.12', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Sat, 27 Sep 2025 06:26:14 GMT', 'Content-Length': '55'})
HTTP response body: b'{"code":"unauthorized","message":"unauthorized access"}'

[2025-09-27T06:26:14.603+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=daily_optimization_suggestions, task_id=query_influx_data, execution_date=20250927T062608, start_date=20250927T062613, end_date=20250927T062614
[2025-09-27T06:26:14.619+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 3 for task query_influx_data ((401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': 'v2.7.12', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Sat, 27 Sep 2025 06:26:14 GMT', 'Content-Length': '55'})
HTTP response body: b'{"code":"unauthorized","message":"unauthorized access"}'
; 570)
[2025-09-27T06:26:14.652+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-09-27T06:26:14.666+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
